//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.11
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 1630b360-2d64-4f8b-b091-63970f8726c3 aws-my-sample-app-android-v0.11";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:0d570053-f3d4-450a-acea-3768250892e7";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "da9f0a62a8614e5c8afe09f0f54aaca9";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "ecseproject-userfiles-mobilehub-1616544663";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_bJOiakccz";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "60n8ebs26hc5s00gjsde9hgkn7";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1gr4t07jhk8ql1an0in9aa8q04m4ribb7d79vlee31uvog1ki0dr";
}
